version: '3.7'

services:

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - '80:80'
            - “443:443”
        volumes:
            # переносимо nginx.conf sites-available
            - /mnt/Plus/nginx:/etc/nginx/
            # тека з веб-проектами
            - /mnt/Plus/WWW:/var/www/
            # логи nginx
            - /mnt/Plus/nginx-log:/var/log/nginx
        #logging:
        #    options:
        #        max-size: 1g
        restart: always




    


    



