version: '3.7'

services:

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # nginx configs
            - ./nginx/conf.d:/etc/nginx/conf.d
            # projects folder
            - ./WWW:/var/www/
            # nginx logs
            - ./nginx-logs:/var/log/nginx
        #logging:
        #    options:
        #        max-size: 1g
        restart: always




    


    



